import { readdir } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Config } from "../../config.js";
import { runTool } from "../toolResult.js";

/**
 * Lists `.md` snapshot files under `snapshotDir`.
 *
 * @param snapshotDir - Root directory where snapshots are written.
 * @param className - Restrict the search to this class's subdirectory (default: search all classes).
 * @param objectId - Restrict the search to files whose name starts with this objectId (default: no filter).
 * @returns Sorted list of matching snapshot file paths.
 */
const listSnapshotFiles = async (
  snapshotDir: string,
  className?: string,
  objectId?: string,
): Promise<string[]> => {
  const classNames = className ? [className] : await readdir(snapshotDir).catch(() => []);
  const files: string[] = [];

  for (const dirClassName of classNames) {
    const dirPath = join(snapshotDir, dirClassName);
    const entries = await readdir(dirPath).catch(() => []);
    for (const entry of entries) {
      if (!entry.endsWith(".md")) continue;
      if (objectId && !entry.startsWith(`${objectId}_`)) continue;
      files.push(join(dirPath, entry));
    }
  }

  return files.sort();
};

/**
 * Registers the `parse_list_snapshots` MCP tool, used to browse the audit trail left by `parse_update`/`parse_delete`.
 *
 * @param server - MCP server to register the tool on.
 * @param config - Resolved app config (used for `snapshotDir`).
 */
export const registerSnapshotTools = (server: McpServer, config: Config): void => {
  server.registerTool(
    "parse_list_snapshots",
    {
      description:
        "List .md snapshot files generated by parse_update/parse_delete, filterable by class and/or objectId.",
      inputSchema: {
        className: z.string().optional(),
        objectId: z.string().optional(),
      },
    },
    async ({ className, objectId }) =>
      runTool(async () => {
        const files = await listSnapshotFiles(config.snapshotDir, className, objectId);
        return { files };
      }),
  );
};
